---
  # AWS Credentials
  aws_access_key: ""
  aws_secret_key: ""

  aws_region:     "us-east-1"

  # VPC Information
  vpc_name:       "MyVPC"
  vpc_cidr_block: "11.10.0.0/16"

  #subnet
  subnet_name : "mysubnet"
  subnet_cidr1: 11.10.0.0/24
  subnet_cidr2: 11.10.1.0/24
  subnet_cidr3: 11.10.2.0/24

  # Internet Gateway Name
  igw_name: "Traffic IGW"




