vpc_cidr_block: "11.10.0.0/16"
vpc_name:       "MyVPC"

subnet_name : "mysubnet"
subnet_cidr1: 11.10.0.0/24
subnet_cidr2: 11.10.1.0/24
subnet_cidr3: 11.10.2.0/24

aws_access_key: ""
aws_secret_key: ""
region: "us-east-1"